batch_size: 64
best_val_acc: 0.715718418514947
best_val_loss: 0.5728349247265879
conditions:
- no_glove
- passive_glove
- active_glove
epochs: 150
lr: 0.001
model_type: CNNLSTM
n_channels: 32
overlap_ms: 100
subjects:
- S1
- S2
- S3
- S4
- S5
- S6
- S7
- S8
- S9
- S10
task: open_close
total_segments: 86
total_windows: 25924
window_ms: 200
