subj_identifier: 'S0' # the unique identifier for the subject
sleeve: true # true if the EMG sleeve is used, false if bipolar electrodes are used

task_open_close:
  sessions_open_loop: [1,2,3] # valid sessions numbers in open-loop modality
  sessions_closed_loop: [4,5] # valid sessions numbers in closed-loop modality
  invalid_sessions: [] # sessions to be ignored for data corruption or other reasons
  model_type: 'LSTM'
  seq_len: 5
task_grasp_patterns:
  sessions_open_loop: [6,7] # valid sessions numbers in open-loop modality
  sessions_closed_loop: [8,9] # valid sessions numbers in closed-loop modality
  invalid_sessions: [] # sessions to be ignored for data corruption or other reasons
  model_type: 'LSTM'
  seq_len: 5
task_single_fingers:
  sessions_open_loop: [10,11] # valid sessions numbers in open-loop modality
  sessions_closed_loop: [12] # valid sessions numbers in closed-loop modality
  invalid_sessions: [] # sessions to be ignored for data corruption or other reasons
  model_type: 'LSTM'
  seq_len: 5